import { Baloo_Bhai_2 } from "next/font/google";
import "./globals.css";

const balooBhai2 = Baloo_Bhai_2({
  variable: "--font-baloo",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700', '800'],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${balooBhai2.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
